### ISSUE TITLE
Zero width joiner in Nehemiah 1:4

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#10]
The line reads:

> \v 4 ਤਾਂ ਐਉਂ ਹੋਇਆ ਕਿ ਜਦ ਮੈਂ ਏਹ ਗੱਲਾਂ ਸੁਣੀਆਂ ਤਾਂ ‍**ਮੈਂ** ਬੈਠ ਕੇ ਰੋਣ ਲੱਗ ਪਿਆ ਅਤੇ ਮੈਂ ਕਈ ਦਿਨਾਂ ਤੀਕ ਸੋਗ ਕੀਤਾ ਅਤੇ ਵਰਤ ਰੱਖਿਆ ਨਾਲੇ ਅਕਾਸ਼ ਦੇ ਪਰਮੇਸ਼ੁਰ ਦੇ ਸਨਮੁੱਖ ਪ੍ਰਾਰਥਨਾ ਕੀਤੀ

It's found in the 11th word ‍**ਮੈਂ**
The codepoint U+200D appears nowhere else in the work. It may be a typo.
In Notepad++ it doesn't render as part of the glyph.  Some editors just do not display it.

**Comment by DavidHaslam** [comment]
I have just fixed this in my fork of master.

**Comment by DeepaRani3012** [comment]
Corrected

**Comment by DavidHaslam** [comment]
This issue is not fixed. The **zero width joiner U+200D** is still present in **Nehemiah 1:4**.

Below is my latest analysis of the concatenated USFM file. 

[merged.usfm.character.frequency.txt](https://github.com/tfbf/punjabi_bible_1945/files/693554/merged.usfm.character.frequency.txt)

NB. Apologies for using **merged.usfm** as a filename, when the word _merged_ has a different meaning in git.

Why did [DeepaRani3012](https://github.com/DeepaRani3012) think that this was corrected?

A _zero width_ character cannot be seen in some environments, so it's no use merely judging by appearance.

Search for the codepoint using Notepad++ regexp **\x{200D}**

![screenshot 2017-01-09 13 43 29](https://cloud.githubusercontent.com/assets/16325414/21768567/24a68b0a-d672-11e6-985f-177ce67dc8f2.png)

**Comment by DavidHaslam** [comment]
[Joshy](https://github.com/joshykurian) - please reopen this issue!

**Comment by DavidHaslam** [comment]
The ZWJ is still present today even after the latest commits and merge by [Joshy](https://github.com/joshykurian).

[merged.usfm.character.frequency.txt](https://github.com/tfbf/punjabi_bible_1945/files/699046/merged.usfm.character.frequency.txt)

**Comment by DavidHaslam** [comment]
I did **not** address this in the commits that were merged in pull request #96

**Comment by DavidHaslam** [comment]
A further commit to my fork today fixes this issue.

**Comment by DavidHaslam** [comment]
This was fixed by the merge of pull request #107

**Comment by DavidHaslam** [comment]
Confirmation evidence:

[merged.usfm.character.frequency.txt](https://github.com/tfbf/punjabi_bible_1945/files/726830/merged.usfm.character.frequency.txt)

The ZWJ is now absent.
