### ISSUE TITLE
The rules for using the Gurmukhi Virama do not allow it to follow a vowel sign

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#104]
**Halant (Virama)** - The character used after a consonant to "strip" it of it's inherent vowel. A Halant follows all but the last consonant in every Gurmukhi syllable.

The following table lists the counts for all the glyphs in the Punjabi Bible that contain a **Virama**.

I have highlighted the second glyph in red because it's the sole instance of a Virama having been keyed after a vowel sign. I am persuaded that it's not valid to do this, even though the **Unicode Normalization** rules for Gurmukhi do **not** specify a _canonical order_ for the diacritics.

![image](https://cloud.githubusercontent.com/assets/16325414/22160992/25eb9b0a-df40-11e6-9378-59cfdaffce1c.png)

The suspect glyph is found in **Acts 2:2** which reads:

> \v 2 ਅਰ ਅਚਾਨਕ ਆਕਾਸ਼ ਤੋਂ ਇੱਕ ਗੂੰਜ ਆਈ ਜਿਹੀ ਵੱਡੀ ਭਾਰੀ ਅ**ਨੇ੍**ਰੀ ਦੇ ਵਗਣ ਦੀ ਹੁੰਦੀ ਹੈ ਅਤੇ ਉਸ ਨਾਲ ਸਾਰਾ ਘਰ ਜਿੱਥੇ ਓਹ ਬੈਠੇ ਸਨ ਭਰ ਗਿਆ ।

Please review and comment.

**Comment by simaksonia417** [comment]
corrected

**Comment by DavidHaslam** [comment]
It's of interest that the SWORD filter **algorithmic transliteration by ICU** barfed on this location!

> Acts 2:2: ara acānaka ākāśa tōṁ ika gūja ā'ī jihī vaḍī bhārī **anērī** dē vagaṇa dī hudī hai atē usa nāla sārā ghara jithē ōha baiṭhē sana bhara gi'ā .

The transliterated word ends up with this:
U+E04D		1	<private-use-E04D>

This was the word with the vowel before the virama.

Interesting find.
