### ISSUE TITLE
Unmatched single quotation mark in John 1:23

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#11]
The line reads:

This line has nested quotes:

\v 23 ਯੂਹੰਨਾ ਨੇ ਉਨ੍ਹਾਂ ਨੂੰ ਨਬੀ ਯਸਾਯਾਹ ਦੇ ਸ਼ਬਦ ਆਖੇ:“ਮੈਂ ਉਜਾੜ ਵਿੱਚ ਹੋਕਾ ਦੇਣ ਵਾਲੇ ਬੰਦੇ ਦੀ ਅਵਾਜ਼ ਹਾਂ:‘ਪ੍ਰਭੂ ਲਈ ਸਿਧਾ ਰਾਹ ਤਿਆਰ ਕਰੋ।”

The left single quotation mark is unmatched. I think the line should read:

\v 23 ਯੂਹੰਨਾ ਨੇ ਉਨ੍ਹਾਂ ਨੂੰ ਨਬੀ ਯਸਾਯਾਹ ਦੇ ਸ਼ਬਦ ਆਖੇ:“ਮੈਂ ਉਜਾੜ ਵਿੱਚ ਹੋਕਾ ਦੇਣ ਵਾਲੇ ਬੰਦੇ ਦੀ ਅਵਾਜ਼ ਹਾਂ:‘ਪ੍ਰਭੂ ਲਈ ਸਿਧਾ ਰਾਹ ਤਿਆਰ ਕਰੋ।’”

**Comment by joshykurian** [comment]
Resolved

**Comment by DavidHaslam** [comment]
Resolution checked and confirmed.
