### ISSUE TITLE
GURMUKHI SIGN ADAK BINDI - single occurrence in Isaiah 48:6

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#12]
The line reads:

\v 6 ਤੈਂ ਸੁਣਿਆ, ਏਹ ਸਭ ਕੁਝ ਵੇਖ, ਅਤੇ ਤੁਸੀਂ, - ਭਲਾ, ਤੁਸੀਂ ਨਾ ਦੱਸੋਗੇ ? ਹੁਣ ਤੋਂ ਮੈਂ ਤੈਨੂੰ ਨਵੀਆਂ ਗੱਲਾਂ ਸੁਣਾਉਂਦਾ ਹਾਂ, ਅਤੇ ਗੁਪਤ ਗੱਲਾਂ ਜਿਨ੍ਹਾਂ ਨੂੰ ਤੈਁਂ ਨਹੀਂ ਜਾਣਿਆ |

The sign is in the last but two word ਤੈਁਂ
Codepoint U+0A01 was found nowhere else in the work.
The codepoint does not render in Notepad++. Some editors may ignore it.

Needs expert attention to decide whether this is a real issue, or merely a rare occurrence.
If it was intended, there may be rendering issues for some fonts.
(e.g.) It doesn't render as part of the glyph in Unicode font **Code2000**.

**Comment by DeepaRani3012** [comment]
Word corrected

**Comment by DavidHaslam** [comment]
Correction checked and confirmed.
