### ISSUE TITLE
Fraction ¾ might be preferred to 3/4 in 2 Chronicles 1:17

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#13]
The line reads:

\v 17 ਸੁਲੇਮਾਨ ਦੇ ਵਿਉਪਾਰੀ ਮਿਸਰ ਤੋਂ ਇੱਕ ਰੱਥ ਚਾਂਦੀ ਦੇ 15 ਪੌਂਡ ਦਾ ਅਤੇ ਇੱਕ ਘੋੜਾ ਚਾਂਦੀ ਦੇ 3 3/4 ਪੌਂਡ ਦਾ ਖਰੀਦਦੇ ਸਨ। ਫ਼ੇਰ ਉਨ੍ਹਾਂ ਨੇ ਇਹ ਘੋੜੇ ਅਤੇ ਰੱਥ ਹਿੱਤੀ ਲੋਕਾਂ ਦੇ ਰਾਜਿਆਂ ਅਤੇ ਆਰਾਮ ਦੇ ਰਾਜਿਆਂ ਨੂੰ ਵੇਚ ਦਿੱਤੇ।

Codepoint U+00BE VULGAR FRACTION THREE QUARTERS might be better here:

The line would then read:
\v 17 ਸੁਲੇਮਾਨ ਦੇ ਵਿਉਪਾਰੀ ਮਿਸਰ ਤੋਂ ਇੱਕ ਰੱਥ ਚਾਂਦੀ ਦੇ 15 ਪੌਂਡ ਦਾ ਅਤੇ ਇੱਕ ਘੋੜਾ ਚਾਂਦੀ ਦੇ 3¾ ਪੌਂਡ ਦਾ ਖਰੀਦਦੇ ਸਨ। ਫ਼ੇਰ ਉਨ੍ਹਾਂ ਨੇ ਇਹ ਘੋੜੇ ਅਤੇ ਰੱਥ ਹਿੱਤੀ ਲੋਕਾਂ ਦੇ ਰਾਜਿਆਂ ਅਤੇ ਆਰਾਮ ਦੇ ਰਾਜਿਆਂ ਨੂੰ ਵੇਚ ਦਿੱਤੇ।

**Comment by beniza** [comment]
Thank you, David. It looks better with ¾. Corrected.
