### ISSUE TITLE
No break spaces in JUDE

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#16]
Please replace ALL 32 **no-break spaces** (U+00A0) in JUDE by ordinary spaces.

Currently the file 66_JUDFBPa.usfm is not valid USFM.

**Comment by DavidHaslam** [comment]
Also please determine the root cause and take steps to prevent reoccurrence.

See [Eight Disciplines Problem Solving](https://en.wikipedia.org/wiki/Eight_Disciplines_Problem_Solving)

**Comment by DavidHaslam** [comment]
See also the same problem in some header tags in Matthew and Mark.

**Comment by DavidHaslam** [comment]
These editing errors were corrected in my [pull 52](https://github.com/tfbf/punjabi_bible_1945/pull/52).

I suspect the root cause was having a shift key depressed when adding the spaces.
This wouldn't normally be a problem for an ordinary keyboard, but I can well imagine that a special keyboard for typing Gurmukhi might behave like this.

I will therefore close the issue. If the team can provide a better explanation for the cause, then feel free to add a further comment.

**Comment by joshykurian** [comment]
Is this issue still there?

**Comment by DavidHaslam** [comment]
No - these had all been corrected in [tfbf/punjabi_bible_1945](https://github.com/tfbf/punjabi_bible_1945/) when I last did a sync yesterday. Maybe even before your last merge.

btw. I've not yet got round to doing a new sync today.
