### ISSUE TITLE
Leading full stops in Job 3:22 ?

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#17]
The verse reads:

\v 22 ....... ਡਾਢੇ ਅਨੰਦ ਹੁੰਦੇ, ਅਤੇ ਖ਼ੁਸ਼ੀ ਕਰਦੇ ਜਦ ਕਬਰ ਨੂੰ ਪਾ ਲੈਂਦੇ ਹਨ,

Is there something missing? 

Google Translate gives:
\v 22 ....... when fierce joy, and happiness, they find the grave,

cf. The KJV has:
22. Which rejoice exceedingly, _and_ are glad, when they can find the grave?

**Comment by DeepaRani3012** [comment]
Corrected. A word was missing.

**Comment by DavidHaslam** [comment]
The correction was included in Joshy's merge #81 today.

I have confirmed the solution, so I will close the issue.
