### ISSUE TITLE
USFM files don't include "Punjabi Pavitra Bible 1945 Edition"

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#22]
For traceability reasons, it would be sensible for each of the 66 USFM files to include

\rem Punjabi Pavitra Bible 1945 Edition

NB. The final "a" in Pavitra is missing from your **README.md** file.

**Comment by DavidHaslam** [comment]
Aside: This Wikipedia page needs to be expanded or a new page creating.

[Bible translations into the languages of India](https://en.wikipedia.org/wiki/Bible_translations_into_the_languages_of_India#North_Indian_languages)

**Comment by DavidHaslam** [comment]
See also issue #7

**Comment by DavidHaslam** [comment]
Fixed in my branch of tfbf/punjabi_bible_1945
In all 66 USFM files, line 3 was inserted by means of a simple TextPipe filter.
This branch is 7 commits ahead of tfbf:master.

**Comment by joshykurian** [comment]
Corrected
