### ISSUE TITLE
Bibledit - open source Bible editing software

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#23]
Is the team familiar with [Bibledit](http://bibledit.org/)?

I doubt it integrates with GitHub, but it is a possible alternative to [ParaTExt](http://paratext.org/).
i.e. Especially for projects independent of the leading Bible Agencies and Bible Societies.

**Comment by DavidHaslam** [comment]
Also of potential interest is [MissionAssist UK](https://home.missionassist.org.uk/).

They have expertise in **Keyboarding** for digitization of legacy Bible translations.

**Comment by beniza** [comment]
I tried setting up a Bible Edit project, but the interface wasn't very easy to use. Now that ParaTExt 8 is going to be "free" (limited edition) for all, we are considering using P8 for our digitization. I'm also in touch with BFBS to see if we can push these files into DBL.

**Comment by beniza** [comment]
Reg. MissionAssist, will they be able to help us in Tamil, Kannada, Bengali and Assamese languages? I have scans of the Bibles in Public domain, but need help in digitizing. Thanks.

**Comment by DavidHaslam** [comment]
The best answer would be to approach them directly through their website.
Their CEO lives here in the UK not far from my home.
I was due to have a second meeting with him a couple of months ago, but never got round to arranging it.

One of the most helpful observations I learned from MissionAssist is their keyboarding procedure always makes use of two independent people for the digitization task. It being unlikely that two persons make the same errors in the same locations, systematic comparison can eliminate the majority of transcription mistakes. This procedure is far superior to OCR even for Latin script languages.

**Comment by DavidHaslam** [comment]
The keyboarding software used by MissionAssist is called [Easy-Key](http://home.easy-key.info/).

It's much simpler than either ParaTExt or Bibledit. It's certainly worth knowing about.

It's free to download through their special [Download Manager](http://home.easy-key.info/index.php/software/downloads).

I still have an earlier version installed in my Windows 7 PC, that I looked at out of curiosity.

**Comment by DavidHaslam** [comment]
In Windows, I mostly use [Notepad++](https://notepad-plus-plus.org/) and [BabelPad](http://www.babelstone.co.uk/Software/BabelPad.html) for Unicode text editing.

btw. I developed my own USFM syntax highlighting file for Notepad++.

See https://github.com/DavidHaslam/USFM

**Comment by DavidHaslam** [comment]
CrossWire has a wiki page called [DevTools:Text Editors](https://crosswire.org/wiki/DevTools:Text_Editors)

**Comment by DavidHaslam** [comment]
This issue was mainly to exchange information.

It has served that purpose and may now be closed.

**Comment by beniza** [comment]
I thought I'll capture these ideas somewhere and then close this one.

**Comment by beniza** [comment]
I've created a [wiki page](https://github.com/tfbf/punjabi_bible_1945/wiki/Tools-for-Bible-Editing)

**Comment by DavidHaslam** [comment]
Thanks.
