### ISSUE TITLE
Unexpected digit 5 at the start of the text in John 1:15

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#25]
The verse reads:

\v 15 5ਯੂਹੰਨਾ ਨੇ ਲੋਕਾਂ ਨੂੰ ਉਸਦੇ ਬਾਰੇ ਦਸਿਆ ਅਤੇ ਆਖਿਆ, “ਇਹੀ ਉਹ ਹੈ ਜਿਸ ਬਾਰੇ ਮੈਂ ਦੱਸ ਰਿਹਾ ਸੀ। ਮੈਂ ਤੁਹਾਨੂੰ ਦਸਿਆ ਸੀ ਕਿ ਉਹ ਇੱਕ,ਜਿਹੜਾ ਮੇਰੇ ਬਾਦ ਆਵੇਗਾ, ਉਹ ਮੈਥੋਂ ਵੀ ਮਹਾਨ ਹੈ। ਉਹ ਮੈਥੋਂ ਵੀ ਪਹਿਲਾਂ ਰਹਿ ਰਿਹਾ ਸੀ।’”

I suspect the digit 5 in the first word (5ਯੂਹੰਨਾ) is a typo.

**Comment by joshykurian** [comment]
Resolved.

**Comment by DavidHaslam** [comment]
Resolution checked and confirmed.

**Comment by DavidHaslam** [comment]
NB. The error was previously _misreported_ by me as being in the **First Epistle of John**, when it was in fact in the **Gospel of John**.
