### ISSUE TITLE
Double GURMUKHI VOWEL SIGN AA found in Esther 3:20

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#30]
The verse reads:

\v 20 ਅਸਤਰ ਨੇ ਨਾ ਆਪਣੇ ਟੱਬਰ ਦਾ, ਨਾ ਆਪਣੀ ਉੱਮਤ ਦਾ ਪਤਾ ਦੱਸਿਆ ਕਿਉਂ ਜੋ **ਮਾਾਰਦਕਈ** ਨੇ ਉਸ ਨੂੰ ਤਗੀਦ ਕੀਤੀ ਹੋਈ ਸੀ ਅਰ ਅਸਤਰ ਮਾਰਦਕਈ ਦਾ ਹੁਕਮ ਓਦਾਂ ਹੀ ਮੰਨਦੀ ਸੀ ਜਿਦਾਂ ਉਹ ਉਹ ਦੇ ਕੋਲ ਪਲਦੀ ਸੀ

The double AA sign is found in the word **ਮਾਾਰਦਕਈ**. Looks like the double AA sign is a typo.
The same word but with a single AA sign is found 57 times in the whole work.

Double identical vowel signs do not render properly with some Unicode fonts, such as Code2000.
Unicode text editors vary in how they display them, so it's not always easy to spot.

**Comment by johnsonldh** [comment]
Resolved the issue
