### ISSUE TITLE
Double GURMUKHI VOWEL SIGN AI found in Ezekiel 25:6

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#33]
The verse reads:

\v 6 ਪ੍ਰਭੁ ਯਹੋਵਾਹ ਐਉਂ ਫ਼ਰਮਾਉਂਦਾ **ਹੈੈ**, - ਏਸ ਲਈ ਕਿ ਤੈਂ ਤਾਉੜੀਆਂ ਵਜਾਈਆਂ ਅਤੇ ਆਪਣੇ ਪੈਰ ਧਰਤੀ ਤੇ ਮਾਰੇ ਅਤੇ ਇਸਰਾਏਲ ਦੀ ਭੂਮੀ ਲਈ ਜਾਨ ਨਾਲ ਸਾਰੀ ਨਿਆਦਰੀ ਕਰ ਕੇ ਅਨੰਦ ਹੋਏ

The double AI sign is located in word **ਹੈੈ**.

This is the sole instance. Must be a typo. Should be a single AI sign.

Same observations about font rendering as in previous issue.

**Comment by DeepaRani3012** [comment]
Corrected

**Comment by DavidHaslam** [comment]
This correction was included in Joshy's merge #81 today.

I have confirmed the solution, so the issue can be closed.
