### ISSUE TITLE
Double GURMUKHI ADDAK found in (e.g.) Numbers 4:13

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#37]
The verse reads:

\v 13 ਤਾਂ ਉਹ ਜਗਵੇਦੀ ਦੀ ਸੁਆਹ **ਕੱੱਢ** ਕੇ ਉਸ ਉੱਤੇ ਬੈਂਗਣੀ ਕੱਪੜਾ ਵਿਛਾਉਣ |

The double ADDAK is located in word **ਕੱੱਢ**. This is just one example.

There are a total of 107 instances of the double ADDAK in the whole work.
Suggest search and replace double ADDAK by single ADDAK.

Same observations about font rendering as per previous issues.

**Comment by DeepaRani3012** [comment]
Issue resolved and pull request made.

**Comment by DavidHaslam** [comment]
Were all 107 instances corrected? Please confirm!
