### ISSUE TITLE
Latin letters 'gh' found in verse text in Micah 3:9

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#38]
The verse reads:

> \v 9 **gh**ਹੇ ਯਾਕੂਬ ਦੇ ਘਰਾਣੇ ਦੇ ਮੁਖਿਓ, ਹੇ ਇਸਰਾਏਲ ਦੇ ਘਰਾਣੇ ਦੇ ਆਗੂਓ, ਏਹ ਸੁਣਿਓ ! ਤੁਸੀਂ ਜੋ ਇਨਸਾਫ਼ ਤੋਂ ਘਿਣ ਕਰਦੇ ਹੋ, ਅਤੇ ਸਾਰੀ ਸਿਧਿਆਈਨੂੰ ਮਰੋੜਦੇ ਹੋ,

The first two letters must surely be a typo!

**Comment by DavidHaslam** [comment]
Two other verses in Micah begin with the same two words (without the gh).

> \v 7 **ਹੇ ਯਾਕੂਬ** ਦੇ ਘਰਾਣੇ, ਇਉਂ ਆਖੀਦਾ ਹੈ ? ਕੀ ਯਹੋਵਾਹ ਦਾ ਆਤਮਾ ਬੇਸਬਰ ਹੈ ? ਭਲਾ, ਏਹ ਉਹ ਦੇ ਕੰਮ ਹਨ ? ਕੀ ਮੇਰੇ ਬਚਨ ਸਿੱਧੇ ਚਾਲ ਚੱਲਣ ਵਾਲੇ ਦੀ ਭਲਿਆਈ ਨਹੀਂ ਕਰਦੇ ?
> \v 12 **ਹੇ ਯਾਕੂਬ**, ਮੈਂ ਤੁਹਾਨੂੰ ਸਾਰੇ ਦੇ ਸਾਰੇ ਜ਼ਰੂਰ ਇਕੱਠੇ ਕਰਾਂਗਾ, ਮੈਂ ਇਸਰਾਏਲ ਦੇ ਬਕੀਏ ਨੂੰ ਜਮਾ ਕਰਾਂਗਾ, ਮੈਂ ਓਹਨਾਂ ਨੂੰ ਬਾਸਰਾਹ ਦੀਆਂ ਭੇਡਾਂ ਵਾਂਙੁ ਰਲਾ ਕੇ ਰੱਖਾਂਗਾ, ਇੱਕ ਇੱਜੜ ਵਾਂਙੁ ਜਿਹੜਾ ਉਸ ਦੀ ਜੂਹ ਵਿੱਚ ਹੈ, ਆਦਮੀ ਦੇ ਕਾਰਨ ਓਹ ਜ਼ੋਰ ਕਰਨਗੇ |

The proposed fix therefore is to simply remove the **gh**.

**Comment by DavidHaslam** [comment]
I have just fixed this in my fork of the repo.

**Comment by DeepaRani3012** [comment]
Corrected

**Comment by DavidHaslam** [comment]
This correction was included in Joshy's merge #81 today, so the issue can be closed.

I have confirmed the solution.
