### ISSUE TITLE
Unattached GURMUKHI VOWEL SIGN AU found in 2 CHRONICLES 11:1

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#39]
The verse reads:

\p \v 1 ਜਦ ਰਹਬੁਆਮ ਯਰੂਸ਼ਲਮ ਵਿੱਚ ਆ ਗਿਆ ਤਦ ਉਸ ਨੇ ਇਸਰਾਏਲ ਨਾਲ ਲੜਨ ਲਈ ਯਹੂਦਾਹ ਅਤੇ ਬਿਨ੍ਯਾਮਿਨ ਦੇ ਘਰਾਣਿਆਂ ਵਿੱਚੋਂ ਇੱਕ **ੌਲਖ** ਅੱਸੀ ਹਜ਼ਾਰ ਜੁੱਧ ਦੇ ਚੁਣਵੇਂ ਸੂਰਮੇ ਇੱਕਠੇ ਕੀਤੇ ਤਾਂ ਜੋ ਓਹ ਫੇਰ ਰਾਜ ਨੂੰ ਰਹਬੁਆਮ ਦੇ ਲਈ ਮੋੜ ਲੈਣ  

The AU sign is not attached to a letter in the word **ੌਲਖ**.

This is the sole occurrence.

**Comment by DeepaRani3012** [comment]
corrected.

**Comment by DavidHaslam** [comment]
Thank you. 

_Sole instances are easier to correct than multiple ones._

**Comment by DavidHaslam** [comment]
This correction was included in Joshy's merge #81 today.

I have confirmed the solution, so the issue can be closed.
