### ISSUE TITLE
Unattached GURMUKHI ADDAK found in 1 CHRONICLES 5:26

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#40]
The verse reads:

> \v 26 ਅਤੇ ਇਸਰਾਏਲ ਦੇ ਪਰਮੇਸ਼ੁਰ ਨੇ ਅੱਸ਼ੂਰ ਦੇ ਰਾਜਾ ਪੂਲ ਦੇ ਮਨ ਨੂੰ ਅਤੇ ਅਸ਼ੂਰ ਦੇ ਰਾਜਾ ਤਿਲਗਥ **ੱਪਿਲਨਸਰ** ਦੇ ਮਨ ਨੂੰ ਉਭਾਰਿਆ ਨੂੰ ਗਾਦੀਆਂ ਨੂੰ ਮਨੱਸ਼ਹ ਦੇ ਅੱਧੇ ਗੋਤ ਨੂੰ ਦੇਸੋਂ ਕੱਢ ਕੇ ਲੈ ਗਏ ,ਅਤੇ ਉਨ੍ਹਾਂ ਨੂੰ ਰਲਹ ਅਰ ਹਾਬੋਰ ਅਰ ਹਾਰਾ ਅਰ ਗੋਜ਼ਾਨ ਦੀ ਨਦੀ ਨੂੰ ਲੈ ਆਇਆ |ਓਹ ਅੱਜ ਤੀਕ ਉੱਥੇ ਹੀ ਹਨ ||

The ADDAK is not attached to a letter in the word **ੱਪਿਲਨਸਰ**.

This is the sole occurrence. It must be a typo.

**Comment by RahulMasih** [comment]
Corrected

**Comment by DavidHaslam** [comment]
Correction checked and confirmed.
