### ISSUE TITLE
Latin letter 's' found in verse text at the end of Esther 7:10

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#41]
The verse reads:

> \v 10 ਤਦ ਉਨ੍ਹਾਂ ਨੇ ਹਾਮਾਨ ਨੂੰ ਉਸ ਸੂਲੀ ਉੱਤੇ ਜਿਹੜੀ ਉਸ ਨੇ ਮਾਰਦਕਈ ਲਈ ਬਣਾਈ ਸੀ ਟੰਗ ਦਿੱਤਾ ਤਾਂ ਪਾਤਸ਼ਾਹ ਦਾ ਕ੍ਰੋਧ ਸ਼ਾਂਤ ਹੋਇਆ || **s**

The final " s" is surely a typo!

**Comment by DavidHaslam** [comment]
I have just fixed this in my fork of the repo.

**Comment by DeepaRani3012** [comment]
corrected.

**Comment by DavidHaslam** [comment]
Correction checked and confirmed.
