### ISSUE TITLE
Double GURMUKHI LETTER A found once in Nehemiah 12:35

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#45]
The verse reads:

\v 35 ਅਤੇ ਜਾਜਕਾਂ ਦੀ ਵੰਸ ਵਿੱਚੋਂ ਨਰਸਿੰਗੀਆਂ ਨਾਲ ਯੋਨਾਥਾਨ ਦਾ ਪੁੱਤ੍ਰ, ਉਹ **ਸ਼ਅਅਯਾਹ** ਦਾ ਪੁੱਤ੍ਰ, ਉਹ ਮੱਤਨਯਾਹ ਦਾ ਪੁੱਤ੍ਰ, ਉਹ ਮੀਕਯਾਹ ਦਾ ਪੁੱਤ੍ਰ, ਉਹ ਜ਼ਕੂਰ ਦਾ ਪੁੱਤ੍ਰ, ਉਹ ਆਸਾਫ ਦਾ ਪੁੱਤ੍ਰ

The sole occurrence of double letter A is located in the word **ਸ਼ਅਅਯਾਹ**.
Is this correct? The word transliterates as **śa'a'ayāha**. The KJV here has **Shemaiah**.
It looks suspect to me.

**Comment by DeepaRani3012** [comment]
word corrected

**Comment by DavidHaslam** [comment]
This correction has not yet been fixed.  The word **ਸ਼ਅਅਯਾਹ** still contains two _consecutive_ letter ਅ.

![screenshot 2017-01-09 14 16 11](https://cloud.githubusercontent.com/assets/16325414/21769383/4755a790-d676-11e6-95f9-bc41759caec9.png)

I still think this is not allowed to have **two vowel letters** like this.

**Comment by DavidHaslam** [comment]
[Joshy](https://github.com/joshykurian) - please reopen this issue #45 

Only the user that closed it can reopen it.

**Comment by simaksonia417** [comment]
corrected
