### ISSUE TITLE
Double GURMUKHI LETTER AA found once in 2 SAMUEL 22:36 (missing space?)

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#46]
The verse reads:

\v 36 ਤੈਂ ਆਪਣੇ ਬਚਾਓ ਦੀ ਢਾਲ ਮੈਨੂੰ ਦਿੱਤੀ ਹੈ, ਅਤੇ ਤੇਰੀ ਨਰਮਾਈ ਨੇ ਮੈਨੂੰ **ਵਡਿਆਇਆਆ** ਹੈ

The double letter AA is located in the wrod **ਵਡਿਆਇਆਆ**.
Is this correct? It looks suspect to me. The word transliterates as **vaḍi'ā'i'ā'ā**.

Inserting a space between the two letters AA would make it translate correctly.
Google Translate then gave this:
"You have given me your shield of salvation, and your humility that makes me great."

**Comment by DeepaRani3012** [comment]
corrected

**Comment by DavidHaslam** [comment]
This correction was included in Joshy's merge #81 today.

I have confirmed the solution. The issue can therefore be closed.
