### ISSUE TITLE
Double GURMUKHI LETTER U found twice in Job 15:24,26

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#47]
These two verses read:

\v 24 ਪੀੜ ਤੇ ਦੁਖ **ਉਉਹ** ਨੂੰ ਡਰਾਉਂਦੇ ਹਨ, ਉਸ ਰਾਜੇ ਵਾਂਙੁ ਜੋ ਜੁੱਧ ਲਈ ਤਿਆਰ ਹੈ, ਓਹ ਉਹ ਨੂੰ ਜਿੱਤ ਲੈਂਦੇ ਹਨ,

\v 26 **ਉਉਹ** ਉਸ ਉੱਤੇ ਟੇਢੀ ਧੌਣ ਨਾਲ ਆਪਣੀ ਮੋਟੀ ਮੋਟੀ ਨੋਕਦਾਰ ਢਾਲ ਨਾਲ ਦੋੜਦਾ ਹੈ,

The same word (**ਉਉਹ**) in both verses has the double letter U.
I think they should both be the single letter U. 
Making that change remedied the Google Translate results.

**Comment by joshykurian** [comment]
Resolved.

**Comment by DavidHaslam** [comment]
The correction was included in Joshy's merge #81 today.

I have confirmed the solution. The issue can now be closed.
