### ISSUE TITLE
Versification issues (provisional incomplete analysis)

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#5]
[Versification Issues.txt](https://github.com/tfbf/punjabi_bible_1945/files/672788/Versification.Issues.txt)

NB. The attached report excluded HEBREWS and REVELATION.
The **GBC USFM Preprocessor** utility crashed when these two files were included.

btw. Some NT verse tags with no text are likely to be those listed here
https://en.wikipedia.org/wiki/List_of_Bible_verses_not_included_in_modern_translations

**Comment by DavidHaslam** [comment]
This updated file was done after fixing some tags (reported in other issues).
It's now for the complete set of 66 files. There are 34 versification issues that may require attention.

[Versification Issues.txt](https://github.com/tfbf/punjabi_bible_1945/files/673035/Versification.Issues.txt)

For the verses omitted in some modern translations, there is commonly an explanation in the footnotes.
Although footnotes are not yet transcribed in this digitization, it's worth considering doing so at least for these empty verses. The footnotes may even provide the missing text with the equivalent of "Some manuscripts have ...."

**Comment by DavidHaslam** [comment]
Here is the updated USFM Tag Statistics for the concatenated USFM file.

[merged.usfm.tags.count.txt](https://github.com/tfbf/punjabi_bible_1945/files/673046/merged.usfm.tags.count.txt)

The number of verse tags (31106) is currently greater than that in the KJV (31102).
This analysis should be revisited after the versification issues have been addressed.

**Comment by DavidHaslam** [comment]
There is a swapped verse tag \v and paragraph tag \p in **Matthew 3:13**

The lines read:

\v 
\p 13 ਤਦ ਯਿਸੂ ਗਲੀਲ ਤੋਂ ਯਰਦਨ ਦੇ ਕੰਢੇ ਯੂਹੰਨਾ ਕੋਲ ਉਸ ਦੇ ਹੱਥੋਂ ਬਪਤਿਸਮਾ ਲੈਣ ਨੂੰ ਆਇਆ |

They should read:
\p 
\v 13 ਤਦ ਯਿਸੂ ਗਲੀਲ ਤੋਂ ਯਰਦਨ ਦੇ ਕੰਢੇ ਯੂਹੰਨਾ ਕੋਲ ਉਸ ਦੇ ਹੱਥੋਂ ਬਪਤਿਸਮਾ ਲੈਣ ਨੂੰ ਆਇਆ |

**Comment by DavidHaslam** [comment]
The chapter tag **\c 10** and **\v 1** tag are missing for **John 10** and also for **1 Corinthians 10**.

They both require a paragraph tag **\p** too.

**Comment by DavidHaslam** [comment]
**Acts 1:6** was duplicated along with its **\p** tag. 
Probably a copy & paste error.

**Comment by DavidHaslam** [comment]
After my own corrections to **Matthew 3:13**, **John 10:1**, **1 Corinthians 10:1** and **Acts 1:6** here is an updated versifications issues list.

[Versification Issues 2.txt](https://github.com/tfbf/punjabi_bible_1945/files/674287/Versification.Issues.2.txt)

This would leave 30 **empty verses** to be reviewed. See earlier comments.

**Comment by DavidHaslam** [comment]
Here is the further updated USFM Tag Statistics for the concatenated USFM file.
This was redone after making some of my own provisional corrections, as already noted in this issue.

[merged.usfm.tags.count.txt](https://github.com/tfbf/punjabi_bible_1945/files/674342/merged.usfm.tags.count.txt)

The number of verse tags (31107) is still greater than that in the KJV (31102).
This analysis should be revisited after the remaining versification issues have been addressed.

**Comment by DavidHaslam** [comment]
Please review the verse tags for **Mark 9:43,44**.

The two verses I reported missing in Mark are 9:43 & 9:46.
In modern versions, it's usually verse 44 missing rather than verse 43. See [Mark 9:44/Mark 9:46](https://en.wikipedia.org/wiki/List_of_Bible_verses_not_included_in_modern_translations#Mark_9:44.2FMark_9:46)

**Comment by joshykurian** [comment]
The versification issues for most of the NT files have been corrected.

**Comment by DavidHaslam** [comment]
Let's close this issue. I have just added issue #72 to cover the remaining anomaly.

**Comment by DavidHaslam** [comment]
Was the text for any of the previously empty NT verses supplied from a footnote in the printed 1945 edition?

If so, we need to ensure that the digitised work accurately reflects that aspect of the translation.
