### ISSUE TITLE
Standardize the USFM file extensions

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#59]
After the last merge the 27 NT books have file extension .SFM
The 39 OT books still have file extension .usfm

We should standardize the USFM file extensions so that all 66 books use the same.

**Comment by joshykurian** [comment]
We will change that to .USFM.

Regards,

Joshy Kurian.

**Comment by joshykurian** [comment]
Standardized the USFM file extensions

**Comment by DavidHaslam** [comment]
See issue #61
