### ISSUE TITLE
Copyright information (CC license) missing from NT books

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#7]
Extracted all the lines with the \rem tag from the concatenated USFM files.

[merged.usfm.rem.lines.txt](https://github.com/tfbf/punjabi_bible_1945/files/672811/merged.usfm.rem.lines.txt)

The NT books don't include the CC license.
In these 27 books there are duplicated remarks.

**Comment by beniza** [comment]
I've removed the duplicated remarks (they were the result of a bad regex). I'll add the copyright information.

**Comment by DavidHaslam** [comment]
See also issue #22

**Comment by DavidHaslam** [comment]
Fixed in my branch. I have added the copyright information today.

**Comment by joshykurian** [comment]
Corrected.
