### ISSUE TITLE
Total number of verses = 31104 but the KJV has only 31102

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#72]
Although the **versification issue** of _empty verses_ has been fixed, we have ended up with two verse tags extra compared to the KJV.

Tracking these down will require special tools.

The [GoBibleCreator USFM Preprocessor](https://gbcpreprocessor.codeplex.com/) cannot detect extra verses, as it has no reference versification scheme to compare it with.

The most straightforward way might be to convert the USFM to OSIS XML and then do a trial build of a SWORD module using **osis2mod** with the default versification.

Any extra verse[s] found at the end of a chapter will be appended to the previous verse in the module and a warning will be output to the osis2mod log file (or terminal).

**Comment by DavidHaslam** [comment]
See also issue #5

**Comment by DavidHaslam** [comment]
It isn't necessary to reach proofreading perfection before we do a trial SWORD module build.

I have the necessary tools on my Windows PC to proceed.

**Comment by DavidHaslam** [comment]
I have identified the two extra verses:

- **3John.1.15** is not in the KJV versification.
- **Rev.12.18** is not in the KJV versification.

See [osis2mod.log.txt](https://github.com/tfbf/punjabi_bible_1945/files/696827/osis2mod.log.txt)

**Comment by DavidHaslam** [comment]
The solution is to use **NRSV** as the [alternate versification](https://crosswire.org/wiki/Alternate_Versification).

Include **-v NRSV** as an option when using **osis2mod** to make the SWORD module.

**Comment by beniza** [comment]
Dear David,

I created a wiki page explaining this alternate versification system.(
https://github.com/tfbf/punjabi_bible_1945/wiki/Versification)

Benjamin
