### ISSUE TITLE
Create STATUS.md

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#73]
It would be sensible to create a page to indicate the text development status.

This would discourage casual visitors from grabbing the Punjabi Bible content to republish before proofreading corrections are all in place.

**Comment by beniza** [comment]
David, I agree and thank you :)

It's done (https://github.com/tfbf/punjabi_bible_1945/blob/master/STATUS.md)

**Comment by DavidHaslam** [comment]
Terrific!
