### ISSUE TITLE
Update the LICENSE file to replace the MIT License

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#74]
The USFM files state:

**Creative Commons Attribution-ShareAlike 4.0**

This should be used in the LICENSE file.

**Comment by DavidHaslam** [comment]
The renamed and updated [LICENSE.md](https://github.com/tfbf/punjabi_bible_1945/blob/master/LICENSE.md) file currently states:

> Public Domain
> ==
> This work (Punjabi Bible (ਪੰਜਾਬੀ ਬਾਈਬਲ)) is free of known copyright restrictions.

Should we be more specific by qualifying this **PD** statement in the file as being in the context of **Indian jurisdiction**?

**Comment by DavidHaslam** [comment]
xxx

**Comment by DavidHaslam** [comment]
Still await the answer to the above question.

**Comment by joshykurian** [comment]
This work (Punjabi Bible (ਪੰਜਾਬੀ ਬਾਈਬਲ)) is free of known copyright restrictions.

Read more about Copyright rules of India

Source PDF :

Old Testament (115.6 MB)
New Testament (31.7 MB)

**Comment by joshykurian** [comment]
Public Domain
==
This work (Punjabi Bible (ਪੰਜਾਬੀ ਬਾਈਬਲ)) is free of known [copyright restrictions.](https://en.wikipedia.org/wiki/Copyright_law_of_India)

[Read more about Copyright rules of India](http://copyright.gov.in/documents/copyrightrules1957.pdf)

**Source PDF :**

- [Old Testament](https://ia801502.us.archive.org/16/items/PunjabiBible_OldTestament/Punjabi%20Bible%20OT_%20Full.pdf) (115.6 MB)
- [New Testament](https://ia800205.us.archive.org/3/items/PunjabiBible_NewTestament/Punjabi%20Bible_New%20Testament.pdf) (31.7 MB)

`
