### ISSUE TITLE
Grave accent at the end of Exodus 32:35

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#8]
The line reads:

\v 35 ਅਰ ਯਹੋਵਾਹ ਨੇ ਬੱਛਾ ਬਣਾਉਣ ਦੇ ਕਾਰਨ ਜਿਹ ਨੂੰ ਹਾਰੂਨ ਨੇ ਬਣਾਇਆ ਸੀ ਲੋਕਾਂ ਨੂੰ ਮਾਰਿਆ ||`

I suspect the grave accent is spurious. Probably a typo.
This codepoint is not found anywhere else in the work.

**Comment by DavidHaslam** [comment]
I have just fixed this in my fork of master.

**Comment by DeepaRani3012** [comment]
Corrected.

**Comment by DavidHaslam** [comment]
Correction checked and confirmed.
