### ISSUE TITLE
Update README.md to indicate the file sizes for the two linked PDF files

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#85]
The PDF files are very large, so we should warn visitors of the size so that they can decide whether they wish to proceed with a download.

cf. Some browsers (with or without plugins) do not prompt the user before opening a new tab to display the PDF file. Or the user may have previously ticked a box for _Always take this action for files of this type_.

**Comment by joshykurian** [comment]
Updated Readme with File size.

**Comment by DavidHaslam** [comment]
Thanks!
