### ISSUE TITLE
Left square bracket in Joshua 5:15

### ISSUE THREAD

**Issue by DavidHaslam** [tfbf/punjabi_bible_1945#9]
The line reads:

> \v 15 ਯਹੋਵਾਹ ਦੇ ਸੈਨਾਪਤੀ ਨੇ ਯਹੋਸ਼ੁਆ ਨੂੰ ਆਖਿਆ ਕਿ ਤੂੰ ਆਪਣੇ ਪੈਰੋਂ **ਅ[ਆਪਣੀ** ਜੁੱਤੀ ਲਾਹ ਕਿਉਂ ਜੋ ਜਿੱਥੇ ਤੂੰ ਖੜਾ ਹੈਂ ਉਹ ਥਾਂ ਪਵਿੱਤਰ ਹੈ ਤਾਂ ਯਹੋਸ਼ੁਆ ਨੇ ਓਵੇਂ ਹੀ ਕੀਤਾ ||

It's in the 12th word **ਅ[ਆਪਣੀ**
The codepoint U+005B is not found anywhere else in the work. I suspect it's a typo.

**Comment by beniza** [comment]
Joshy, please have a look at this one.

**Comment by DavidHaslam** [comment]
I think it makes sense to remove the **ਅ[** such that **ਅ[ਆਪਣੀ** becomes the word **ਆਪਣੀ**.

Google then translates the verse as:

> 15 that the commander said to Joshua, you are your legs for where you stand your shoes off, the place is holy Joshua did Oven ||

NB. The last word translated **Oven** is a bit suspicious, but then I don't know any Punjabi.

**Comment by DavidHaslam** [comment]
I have just fixed this in my fork of master.

NB. Not attempted to do anything about the suspiciously translated word.

**Comment by DeepaRani3012** [comment]
Corrected

**Comment by DavidHaslam** [comment]
Correction checked and confirmed.
